### ISSUE TITLE
Coqdoc_to_flm crashes on attached test.v

### ISSUE THREAD

**Issue by palmskog** [rocq-community/proviola#1]
**[Original report](https://bitbucket.org/Carst/proviola-source/issue/1) by Carst Tankink (Bitbucket: [Carst](https://bitbucket.org/Carst), GitHub: [Carst](https://github.com/Carst)).**

----------------------------------------

When processing a simple test file, the export to XML by coqdoc_to_flm fails. 

File attached. 

Console session:
    
    #!console
    $ coqc Test.v
    $ coqdoc Test.v
    $ coqdoc_to_flm Test.html
    

Stack trace:
    
    #!python
    
    File: Test.html
    Traceback (most recent call last):
      File "/home/kbrink/usr/bin/coqdoc_to_flm", line 63, in <module>
        narrated_movie = convert_coqdoc(args.coqdoc_file.read()).toxml()
      File "/home/kbrink/usr/bin/coqdoc_to_flm", line 55, in convert_coqdoc
        p.feed(coqdoc_data)
      File
    "/home/kbrink/rs/coqassignment/proviola-source/converters/coqdoc_to_flm/coqdoc_parser.py",
    line 196, in feed
        self._movie = self._tree_to_movie(self._tree)
      File
    "/home/kbrink/rs/coqassignment/proviola-source/converters/coqdoc_to_flm/coqdoc_parser.py",
    line 175, in _tree_to_movie
        (frames, scenes) = self._process_body(tree.html.body)
      File
    "/home/kbrink/rs/coqassignment/proviola-source/converters/coqdoc_to_flm/coqdoc_parser.py",
    line 157, in _process_body
        (div_frames, div_scenes) = self._process_div(div)
      File
    "/home/kbrink/rs/coqassignment/proviola-source/converters/coqdoc_to_flm/coqdoc_parser.py",
    line 136, in _process_div
        frame = self._html_to_frame(child)
      File
    "/home/kbrink/rs/coqassignment/proviola-source/converters/coqdoc_to_flm/coqdoc_parser.py",
    line 104, in _html_to_frame
        frame = Coqdoc_Frame(command = "(*" + self._get_text(node) + "*)",
    TypeError: cannot concatenate 'str' and 'NoneType' objects

**Comment by palmskog** [comment]
**Original comment by Kasper Brink (Bitbucket: [kbrink](https://bitbucket.org/kbrink), GitHub: [kbrink](https://github.com/kbrink)).**

----------------------------------------

Test.html generated using coqdoc on Kasper's machine (Ubuntu Lucid 10.04.1)

**Comment by palmskog** [comment]
**Original comment by Carst Tankink (Bitbucket: [Carst](https://bitbucket.org/Carst), GitHub: [Carst](https://github.com/Carst)).**

----------------------------------------

I cannot reproduce this issue on my machine. This might have to do with the Python version, but I can't reproduce that. Would you mind running with some debug output so I can verify something?

**Comment by palmskog** [comment]
**Original comment by Kasper Brink (Bitbucket: [kbrink](https://bitbucket.org/kbrink), GitHub: [kbrink](https://github.com/kbrink)).**

----------------------------------------

Upgrading BeautifulSoup from version 3.1.0.1-2build1 (Ubuntu 10.04.1 package) to version BeautifulSoup-3.2.0-py2.6.egg (installed via easy_install) fixes the crash.

Add requirement BeautifulSoup >= 3.2.0 to documentation?

**Comment by palmskog** [comment]
**Original comment by Carst Tankink (Bitbucket: [Carst](https://bitbucket.org/Carst), GitHub: [Carst](https://github.com/Carst)).**

----------------------------------------

Closed, README added in <<changeset 8bf4cf58764d>>. This definitely is a bug in the Ubuntu package of BeautifulSoup.
